apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-with-load-balancer
  namespace: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-with-load-balancer
  template:
    metadata:
      labels:
        app: echo-with-load-balancer
    spec:
      containers:
      - name: echo
        image: nvgl/echo:0.0.3
