apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-with-node-port
  namespace: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-with-node-port
  template:
    metadata:
      labels:
        app: echo-with-node-port
    spec:
      containers:
      - name: echo
        image: nvgl/echo:0.0.3
