kind: Service
apiVersion: v1
metadata:
  name: echo-with-node-port
  namespace: echo
spec:
  type: NodePort
  selector:
    app: echo-with-node-port
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: port
    nodePort: 30000


#
# kubectl get service echo-with-node-port -n echo
#
#NAME                  TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
#echo-with-node-port   NodePort   10.101.175.147   <none>        80:30000/TCP   1m
#
# kubectl get endpoints -n echo
#
#NAME                   ENDPOINTS                                            AGE
#echo-with-cluster-ip   192.168.1.3:8000,192.168.1.4:8000,192.168.2.4:8000   3d
#echo-with-node-port    192.168.1.5:8000,192.168.2.5:8000,192.168.2.6:8000   2m
#
#
#We can join the service on each worker via the 30000 port
#But also with the cluster ip via the 80 port
#
# curl  172.20.95.30:30000
# curl  172.20.95.31:30000
# curl  172.20.95.32:30000
